name: Test
on:
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup pnpm 7
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install Dependencies
        id: deps
        run: pnpm install
      - name: Test
        id: test
        run: pnpm test
